services:
  backend:
    container_name: playoff-backend
    image: roihass/playoff-backend:latest
    ports:
      - '3000:3000'
    env_file:
      - .env.stage.prod
    restart: always
    volumes:
      - ./logs:/app/playoff-backend/logs
    networks:
      - app-network
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: playoff-db
    restart: always
    env_file:
      - .env.stage.prod
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - app-network

volumes:
  pgdata:

networks:
  app-network:
    driver: bridge
